---
- name: install docker on all server
  hosts: all
  tasks:
     - name: dowload the shell script for docker and run it
       shell: "{{item}}"
       with_items:
         - curl -fsSL https://get.docker.com -o install-docker.sh
         - sudo sh install-docker.sh
  
