---
- name: working on docker containers
  hosts: all
  tasks:
    - name: creste a tomcat caontainer
      docker_container:
        name: appserver
        image: tomcat
    - name: delete the tomcat container
      docker_container:
        name: appserver
        state: absent
