---
- name: configure apache2 using multiple child playbooks
  hosts: all
  tasks:
    - name: call multiple child playbooks
      include_tasks: "{{item}}"
      with_items:
          - install.yml  
          - edit_index.yml
          - restart.yml
          - check_url_responce.yml
