---
- name: delete if the file is an empty file
  hosts: all
  tasks:
    - name: capture info about the file
      stat:
        path: /tmp/file1
      register: a
    - name: display output of the above module
      debug:
        var: a
    - name: delete if the file is executable
      file: 
       name: /tmp/file1
       state: absent
      when: a.stat.executable == true   
