---
- name: Create multiple users and copy files into the users home dirs
  hosts: all
  tasks:
    - name: Create users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: Raju,b: intelliqit,c: /home/Raju}
        - {a: Rani,b: intelliqit,c: /tmp/Rani}
    - name: copy files into the users home dirs
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /home/Raju}
        - {a: /etc/group,b: /tmp/Rani}
...
