---
- name: install/uninstall s/w applications
  hosts: all
  vars:
     - a: tomcat10
     - b: present
     - c: yes
  tasks:
     - name: install/uninstall of s/w
       apt:
          name: "{{a}}"
          state: "{{b}}"
          update_cache: "{{c}}"
