---
- name: Check if f1 folder is present if not create a file f1
  hosts: all
  tasks:
    - name: Check for f1 folder
      stat:
        path: f1
      register: a
    - name: Print output of the above modules
      debug:
        var: a
    - name: Create f1 file if f1 folder is not present
      file:
        name: f1
        state: touch
      when: a.stat.exists == false

