---
- name: create user on all servers
  hosts: all
  gather_facts: false
  become: yes
  serial: 2
  tasks:
    - name: user creation
      user: 
       name: anu
       password: intelliq
       home: /tmp/anu
       shell: /bin/bash
       comment: "a regular user"
       uid: 6789

...




  

